#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

console_title_template = "{{ .Shell }} in {{ .Folder }}"
version = 3
final_space = true


[palette]
# Lumon colour pallet
clarity = "#f3ffff"
protocol = "#afcbd6"
membrane = "#beb780"
system = "#79a6b9"
sector = "#20464f"
archive = "#0e1a26"


[var]
rArrow = "󰅂"



# === PROMPT ===

# Prev commands
[transient_prompt]
  background = "transparent"
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}p:system{{end}}"
  ]
  template = "{{ .Var.rArrow }} "


# Multi-line commands
[secondary_prompt]
background = "transparent"
template = ""



# == Current command ==

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  # Path
  [[blocks.segments]]
    type = "path"
    style = "plain"
    background = "transparent"
    foreground = "p:system"
    template = "{{ .Path }}"

    [blocks.segments.properties]
      style = "full"

  # Git
  [[blocks.segments]]
    type = "git"
    style = "plain"
    background = "transparent"
    foreground = "p:protocol"
    template = "  {{ .HEAD }}{{if or (.Working.Changed) (.Staging.Changed)}}*{{end}} {{if gt .Behind 0 }}⇣{{end}}{{if gt .Ahead 0}}⇡{{end}}"

    [blocks.segments.properties]
      branch_icon = ""
      fetch_status = true


[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  # Right Arrow
  [[blocks.segments]]
    type = "text"
    style = "plain"
    background = "transparent"
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}p:system{{end}}"
    ]
    template = "{{ .Var.rArrow }}"

# == Current command ==

# === PROMPT ===